# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firelabs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for firelabs
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'

  target 'firelabsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firelabs-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firelabs-tvOS

  target 'firelabs-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
